export const ITEM_LIST_REQUEST = 'ITEM_LIST_REQUEST';
export const ITEM_LIST_SUCCESS = 'ITEM_LIST_SUCCESS';
export const ITEM_LIST_FAILURE = 'ITEM_LIST_FAILURE';

export const ITEM_DETAILS_REQUEST = 'ITEM_DETAILS_REQUEST';
export const ITEM_DETAILS_SUCCESS = 'ITEM_DETAILS_SUCCESS';
export const ITEM_DETAILS_FAILURE = 'ITEM_DETAILS_FAILURE';

export const BASKET_ADD_ITEM = 'BASKET_ADD_ITEM';
export const BASKET_REM_ITEM = 'BASKET_REM_ITEM';